name = "lapce-discord"
display-name = "Discord Rich Presence"
description = "Discord Rich Presence for Lapce [Testing]"
version = "0.1.0"
author = "TIMMLOPK"


[configuration]
language_id = "rust"
[configuration.options.diagnostics]
enable = false
enableExperimental = false